### ISSUE TITLE
Token - IndexError: list index out of range

### ISSUE THREAD

**Issue by markusEdelhofer** [mattupstate/flask-jwt#136]
If I replace the token with an SPACE (" ") , I got this index out of range error. If I sent a singel other character everything works corecct and I got an error message!

```
Traceback (most recent call last):
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 293, in _decode_jwt_from_request
    encoded_token, csrf_token = get_encoded_token_function()
  File "/home/markus/Development/.virtualenv/wet-mobileapi/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 208, in _decode_jwt_from_headers
    encoded_token = parts[1]
IndexError: list index out of range
```

**Comment by chyok** [comment]
this is flask_jwt_extended [https://github.com/vimalloc/flask-jwt-extended](url)
