### ISSUE TITLE
HAMC failed @ _get_serializer().dumps @ encode_handler @ generate_token

### ISSUE THREAD

**Issue by minhoryang** [mattupstate/flask-jwt#44]
Traceback (most recent call last):
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_restful/__init__.py", line 446, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Volumes/Unsigned/server/application/models/user.py", line 45, in post
    return {'status': 200, 'message': generate_token(user)}  # TODO : SESSION!
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/src/flask-jwt/flask_jwt/__init__.py", line 147, in generate_token
    token = _jwt.encode_callback(payload)
  File "/Volumes/Unsigned/server/application/models/user.py", line 88, in encode_handler
    return t.dumps(payload).decode('utf-8')
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/itsdangerous.py", line 742, in dumps
    return signer.sign(self.dump_payload(header, obj))
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/itsdangerous.py", line 353, in sign
    return value + want_bytes(self.sep) + self.get_signature(value)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/itsdangerous.py", line 348, in get_signature
    sig = self.algorithm.get_signature(key, value)
  File "/usr/local/var/lib/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/itsdangerous.py", line 268, in get_signature
    mac = hmac.new(key, msg=value, digestmod=self.digest_method)
  File "/usr/local/var/lib/pyenv/versions/3.4.2/lib/python3.4/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/var/lib/pyenv/versions/3.4.2/lib/python3.4/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'

**Comment by minhoryang** [comment]
And... I found the issue..
Don't use app.config['secret_key'] not app.config['SECRET_KEY'].

Problem happened, there are no key at HMAC, and HMAC is generated from _get_serializer().
and the key which is used at _get_serializer() is current_app.config['JWT_SECRET_KEY'].
and current_app.config['JWT_SECRET_KEY'] is same as app.config['SECRET_KEY'].

It's not same with app.config['secret_key'].
