### ISSUE TITLE
HMAC(key, msg, digestmod) - key: expected bytes or bytearray, but got 'NoneType'

### ISSUE THREAD

**Issue by s4p0** [mattupstate/flask-jwt#47]
I'm getting the following error, however if I run the example it works quite good!
Then, I don't know if I'm doing something really wrong (as solo, it works!) or is some kind of bug, somehow.

```
Traceback (most recent call last):
  File "\\mypath\.venv\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "\\mypath\.venv\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "\\mypath\.venv\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "\\mypath\.venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "\\mypath\.venv\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "\\mypath\.venv\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "\\mypath\.venv\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "\\mypath\.venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "\\mypath\.venv\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "\\mypath\.venv\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "\\mypath\.venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "\\mypath\.venv\lib\site-packages\flask\views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "\\mypath\.venv\lib\site-packages\flask_jwt\__init__.py", line 154, in post
    token = _jwt.encode_callback(payload)
  File "\\mypath\.venv\lib\site-packages\flask_jwt\__init__.py", line 50, in _default_encode_handler
    return _get_serializer().dumps(payload).decode('utf-8')
  File "\\mypath\.venv\lib\site-packages\itsdangerous.py", line 742, in dumps
    return signer.sign(self.dump_payload(header, obj))
  File "\\mypath\.venv\lib\site-packages\itsdangerous.py", line 353, in sign
    return value + want_bytes(self.sep) + self.get_signature(value)
  File "\\mypath\.venv\lib\site-packages\itsdangerous.py", line 348, in get_signature
    sig = self.algorithm.get_signature(key, value)
  File "\\mypath\.venv\lib\site-packages\itsdangerous.py", line 268, in get_signature
    mac = hmac.new(key, msg=value, digestmod=self.digest_method)
  File "\\mypath\.venv\lib\hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "\\mypath\.venv\lib\hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'
```

my directory structure is as follows:
- app.py
- main.py
- auth.py

where app.py has:
```python
from flask import Flask
# JWT
from flask_jwt import JWT

app = Flask(__name__)
jwt = JWT(app)
```

auth.py:
```python
from app import app, db, jwt
from flask_jwt import jwt_required

class User(object):
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

@app.route('/protected')
@jwt_required()
def protected():
    return 'Success!'

@jwt.authentication_handler
def authenticate(username, password):
    # import pdb; pdb.set_trace()
    if username == 'joe' and password == 'pass':
        return User(id=1, username='joe')

@jwt.user_handler
def load_user(payload):
    if payload['user_id'] == 1:
        return User(id=1, username='joe')
```

and main.py:
```python
from app import app
from auth import *
from api import *
from views import *

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by mattupstate** [comment]
Looks like you didn't specify a secret key.

**Comment by s4p0** [comment]
Sorry. 
But for this version I had it removed. 

I´ve tried both:
```python
app.config['SECRET_KEY'] = 'super-secret'
app.config['JWT_ALGORITHM'] = 'HS256'
```

**Comment by s4p0** [comment]
Why did I close it? sorry guys

**Comment by mattupstate** [comment]
You need to set `app.config['JWT_SECRET_KEY']`

**Comment by s4p0** [comment]
Shit! That was the issue. Thanks a lot @mattupstate.
However, I don't remember seen anything about ``` 'JWT_SECRET_KEY' ``´ on docs.
Weird that solo it works fine.

Anyway, thanks a lot!

**Comment by dedfft** [comment]
Thank you so much for how you solved your problem. It helped me with mine))
