### ISSUE TITLE
Can this be used with Python v2.6.x?

### ISSUE THREAD

**Issue by goterpsgo** [mattupstate/flask-jwt#94]
I'm working on a project that requires using Python v2.6.6 on Centos 6.x. I am using the sample code published by this repo (https://github.com/mattupstate/flask-jwt/blob/master/example/app.py) and python is returning a syntax error from __init__.py:

<pre>Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from main import app as application
  File "./main.py", line 5, in <module>
    from auth import api_auth
  File "./auth.py", line 3, in <module>
    from flask_jwt import JWT
  File "/opt/mist_base/env/lib/python2.6/site-packages/flask_jwt/__init__.py", line 83
    for claim in verify_claims
      ^
SyntaxError: invalid syntax</pre>

I assume this works for other people's instances, and I know there are issues using some libraries with v2.6.x - is this the case?

thx,
- Joe

**Comment by goterpsgo** [comment]
I was informed elsewhere this was indeed the case. I also was able to compile python v2.7.x from source and install it in a custom directory so this issue is now OBE.
